site_name: Jas Brothers
site_url: https://jasbrothers.com/
site_description: Two brothers learning about the world by building advanced robots.

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Blog:
      - Level 2 Programming: blog/level-2-programming.md
      - What a Smart Speaker Actually Costs: blog/what-a-smart-speaker-costs.md
